name: Auto Update my.m3u

on:
  schedule:
    - cron: '0 * * * *'  # Har 1 ghante run
  workflow_dispatch:     # Manual trigger bhi possible

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Latest M3U
        run: |
          curl -s -o my.m3u https://raw.githubusercontent.com/alex8875/m3u/refs/heads/main/jtv.m3u

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add my.m3u
          git diff-index --quiet HEAD || git commit -m "Auto update my.m3u"
          git push
